const CHANGE_CURRENT_PHRASE = 'CHANGE_CURRENT_PHRASE';
const INCREASE_TEAM_POINT = 'INCREASE_TEAM_POINT';
const RESET_POINTS = 'RESET_POINTS';

export { CHANGE_CURRENT_PHRASE, INCREASE_TEAM_POINT, RESET_POINTS };
